### ISSUE TITLE
Usage of underscore

### ISSUE THREAD

**Issue by eric-burel** [OrigenStudio/FS-helpers#5]
Hi, just a very quick note, the package fail to run correctly in test mode, as underscore global variable `_` is not available. Adding underscore to my test dependencies did not solve it.
The fix is simply to make this dependency explicit in the `Package.js` and using `import _ from 'meteor/underscore`.

I'll try to PR this myself if I have some free time. Edit: I did not manage to though :/

Thanks for this lib anyway!

**Comment by ochicf** [comment]
Merged in #6. Thanks!
